yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.author.as_view(), name='author'),
    path('tech/', views.tech.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='home_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from . import constants

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='posts',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:constants.STR_LENGTH]


class Comment(models.Model):
    text = models.TextField(
        'Текст',
        help_text='Текст комментария',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментария'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        unique_together = ('user', 'author')

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .pagination import paginator_context


@cache_page(20, key_prefix='home_page')
def index(request):
    obj = paginator_context(
        Post.objects.select_related('group').all(), request
    )
    context = {"page_obj": obj}
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    obj = paginator_context(
        group.posts.all(),
        request)
    context = {
        "group": group,
        "page_obj": obj
    }
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_count = author.posts.count()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author
    ).exists()
    obj = paginator_context(
        author.posts.all(),
        request)
    context = {
        "author": author,
        "post_count": post_count,
        "following": following,
        "page_obj": obj
    }
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post_id=post_id)
    posts_count = Post.objects.filter(author_id=post.author).count()
    context = {
        "post": post,
        "posts_count": posts_count,
        "form": form,
        "comments": comments
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.id and request.user != post.author:
        return redirect('posts:profile', request.user)
    is_edit = True
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    context = {
        "form": form,
        "is_edit": is_edit
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    obj = paginator_context(Post.objects.select_related('author').filter(
        author__following__user=request.user), request
    )
    context = {
        'page_obj': obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    post_author = get_object_or_404(User, username=username)
    if request.user != post_author:
        Follow.objects.get_or_create(user=request.user, author=post_author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    post_author = get_object_or_404(User, username=username)
    Follow.objects.filter(
        user=request.user,
        author=post_author
    ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %} Новый пост {% endblock %}
{% load user_filters %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}     
            Редактировать пост
            {% else %}
            Новый пост
            {% endif %}
          </div>
          <div class="card-body">      
            <form method="post" enctype="multipart/form-data" action=""> 
              {% csrf_token %}
              {% for field in form %} <p>
                {% if field.errors %}
                  <div class="alert alert-danger">
                    {{ field.errors }}
                  </div>
                {% endif %}
                <strong>{{ field.label }}</strong>
                {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
                {{ field|addclass:'form-control' }}
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} Подписки {% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Избранные авторы</h1>
  <p>
    {% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
  <ul>
    <li>
      {% if post.group %}
      Автор: <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a> |
      Группа: <a href="{% url 'posts:group_posts' post.group.slug %}">
        {{ post.group.title }}</a> 
      {% endif %}
    </li>
    <li>
     {{ post.pub_date|date:"j E Y" }} в {{ post.pub_date|date:"G:i" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends "base.html" %} 
{% block title %} {{ group }} {% endblock %}
{% load thumbnail %}
{% block content %}
<h1>{{ group.title }}</h1>
<p>
  {{ group.description }}
</p>
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
{% for post in page_obj %}
  <p>  
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    <li>
    <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
    <!-- под последним постом нет линии -->
  </div>  
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}
{% load thumbnail %}
{% block title %} Главная страница {% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Последние обновления на сайте</h1>
  <p>
    {% include 'posts/includes/switcher.html' %}
{% cache 20 postslist %}
{% for post in page_obj %}
  <ul>
    <li>
      {% if post.group %}
      Автор: <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a> |
      Группа: <a href="{% url 'posts:group_posts' post.group.slug %}">
        {{ post.group.title }}</a> 
      {% endif %}
    </li>
    <li>
     {{ post.pub_date|date:"j E Y" }} в {{ post.pub_date|date:"G:i" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endcache %}
{% include 'posts/includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %} Пост: {{ post.text|truncatechars:30 }} {% endblock %}
{% load thumbnail %}
{% load user_filters %}
{% block content %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y"}} 
          </li>
          <!-- если у поста есть группа -->   
          <li class="list-group-item">
            Группа: {{ post.group }}
            {% if post.group.slug %}
            <a href="{% url 'posts:group_posts' post.group.slug %}">
              все записи группы
            </a>
            {% else %}
            <a href="{% url 'posts:group_posts' post.group %}">
              все записи группы
            </a>
          </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post_count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside> 
      <article class="col-12 col-md-9">
        <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
         {{ post.text }}
        </p>
        {% if request.user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
        {% endif %}
      </button>
      <p>
      </article>
    </div>
    {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <aside class="col-12 col-md-3">
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %} Профайл пользователя {{ user }} {% endblock %}
{% load thumbnail %}
{% block content %}
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ post_count }} </h3>
        {% if request.user != author %}
        {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
       {% endif %}
       {% endif %}
        <article>
        <p>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          <p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
          {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>
         <p>
          {% if post.group %}   
          <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы </a>        
          {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        <!-- Остальные посты. после последнего нет черты -->
        {% include "posts/includes/paginator.html" %} 
      </div>
    </main>
{% endblock %}